[package]

name          = "compositor"
description   = "Wayland compositor made for AvdanOS"
documentation = "https://docs.avdanos.com/"
homepage      = "https://avdanos.com/"
license       = "GPL-3.0"
version       = "0.0.1"
authors       = ["Akane <simo.ciardo10@gmail.com>", "Froxcey <froxcey@avdanos.com>", "Sammy <sammy99jsp@avdanos.com>"]
edition       = "2021"
build         = "build.rs"

[dependencies]

serde_json    = "1.0.82"
lazy_static   = "1.4.0"
json_comments = "0.2.1"
regex         = "1.6.0"
slog-stdlog   = "4.1.1"
bitflags       = "1"
colored       = "2.0.0"

[dependencies.compositor-macros]

path = "./src/macros"

[dependencies.json-tree]

git = "https://github.com/Sammy99jsp/json-tree.git"
features = ["jsonc"]

[dependencies.smithay]

git      = "https://github.com/smithay/smithay.git"
features = ["desktop", "default"]

[dependencies.serde]

version  = "1.0.141"
features = ["derive"]

[dependencies.slog]

version  = "2.1.1"
features = ["max_level_trace", "release_max_level_warn"]
