[package]

name = "compositor"
description = "Wayland compositor made for AvdanOS"
documentation = "https://docs.avdanos.com/"
homepage = "https://avdanos.com/"
license = "GPL-3.0"
version = "0.0.1"
authors = ["Akane <akane6704@protonmail.com>", "Froxcey <froxcey@avdanos.com>"]
edition = "2021"

[dependencies]

smithay = { git = "https://github.com/smithay/smithay.git" }
wayland-client = { git = "https://github.com/smithay/wayland-rs.git" }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
