[package]
name = "compositor"
description = "Wayland compositor made for AvdanOS"
documentation = "https://docs.avdanos.com/"
homepage = "https://avdanos.com/"
license = "GPL-2.0-or-later"
version = "0.0.1"
authors = ["Akane", "Froxcey <froxcey@avdanos.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smithay = { git= "https://github.com/smithay/smithay.git" }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"

