[package]

name = "compositor"
description = "Wayland compositor made for AvdanOS"
documentation = "https://docs.avdanos.com/"
homepage = "https://avdanos.com/"
license = "GPL-3.0"
version = "0.0.1"
authors = ["Akane <akane6704@protonmail.com>", "Froxcey <froxcey@avdanos.com>", "Sammy <placeholder@email.com>"]
edition = "2021"
build = "build.rs"

[dependencies]

wayland-client = "0.29.4"
wayland-server = "0.29.4"
wayland-protocols = "0.29.4"
serde_json = "1.0.82"
lazy_static = "1.4.0"
json_comments = "0.2.1"
regex = "1.6.0"
slog-stdlog = "4.1.1"

[dependencies.smithay]

git = "https://github.com/smithay/smithay.git"
features = ["desktop", "default"]

[dependencies.serde]

version = "1.0.141"
features = ["derive"]

[dependencies.slog]

git = "https://github.com/slog-rs/slog.git"
features = ["max_level_trace", "release_max_level_warn"]
