[package]

name = "compositor-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]

quote = "1.0.21"
proc-macro2 = "1.0.43"

[dependencies.syn]

version  = "1.0.99"
features = ["full"]
